Resolve io module conflict
Resolve io.py conflict with stdlib io module by renaming io.py to csio.py. Conflict appears in testing as AttributeError: 'module' object has no attribute 'BufferedIOBase'.